### ISSUE TITLE
似乎不应该自动在星号 * （或者是 markdown 语法）和中文文字之间加空格

### ISSUE THREAD

**Issue by chenglu** [openSUSE-zh/discourse-cjk-text-spacing#1]
Hi Team: 

感谢开发出如此优秀的插件给中文的 Discourse 论坛带去了一抹优雅，也带去了对开发者群体的「最基本尊重」。

我遇到一个问题就是，在 [这个帖子里](https://discuss.tf.wiki/t/topic/569)，作者似乎用 markdown 语法进行粗体的标示，但是（应该是经过我们的插件转换后）发帖成功时，markdown 语法 ```**``` 和中文文字之间就加入了一个空格，这就导致了文章里中文的加粗失效，不知道你们是否遇到过这样的问题？

谢谢！

**Comment by chenglu** [comment]
Discourse 版本 2.6.0.beta2 (cff57c1883)
系统运行在 Ubuntu 18.04 64位

**Comment by chenglu** [comment]
![image](https://user-images.githubusercontent.com/2258420/95282940-17f0cc80-088d-11eb-9f80-2b78ebb88a76.png)

我看最近更新了新版，但实际上问题还是存在的 @marguerite 
建议加一个「星号和中文文字」之间不加空格的 exception

**Comment by marguerite** [comment]
@chenglu 这似乎是 auto-correct gem 的 bug，自动加空格是这个 Ruby China 开发的 gem 的功能，他们只用在 title 上面应该遇不到你这个问题。

我可以在我这边修，但那样你也还是不好装。我看看能不能直接交到他们那边去

**Comment by chenglu** [comment]
感谢回复，期待可以有解决方法，感谢～
@marguerite

**Comment by marguerite** [comment]
@chenglu 

https://github.com/huacnlee/auto-correct/blob/master/lib/auto-correct/format.rb

问题出在这里：

    rule "#{CJK}", '[\|+$@#*]', space: true, reverse: true

它的意思是说只要 CJK 字符的前后出现了那些特殊字符，就加空格。这就与 markdown 违背了。

改这个把里面的 @#* 全部去掉就可以了。@ 是 @ discourse 用户名，# 是 discourse hashtag 和 markdown 的标题，* 号就是你要的东西。上游 auto-correct 可能有它别的考虑。我仅就 discourse 考虑这三个是应该去掉的。你自己去一下应该就没问题了，至于别的 case 会不会因为没有这个规则而出问题，我还没有想到什么 case 能这样。

**Comment by chenglu** [comment]
按照这个思路，我试着 fork 并修改了一下 auto-correct，[CI 显示了一些 test 的错误](https://travis-ci.com/github/chenglu/auto-correct/builds/189625816#L299)，但「又不是不能用」——至少星号前后没有空格了。

我看了一下 go 语言的实现，在 Go Play Ground 上进行了一个测试：
https://play.golang.org/p/NYX6Co2hYrm

因此现有的规则，看起来 # 和 @ 是没问题的，有问题的仍是星号 *，所以我在想是否可以找到对 # 或者 @ 特殊处理的代码，然后加一个针对 * 的特殊处理，这是否也是一种可以解决问题的办法？

**Comment by chenglu** [comment]
@marguerite 

另外由于太小白了我，不知道… 就算咱们讨论了一个比较好的方案，
具体怎样才能让 Discourse 插件使用我们修改过的 auto-correct 呢？

关于规则的话，我最近想到的其实就是：只排除 * + CJK 这一个 case，也就是把 * 和 CJK 之间的空格去掉就行，
我看到了 https://github.com/huacnlee/auto-correct/blob/master/lib/auto-correct/format.rb
文件中可能有类似的东西存在，但是目前还没有特别去尝试。

跟进如上，感谢！

**Comment by huacnlee** [comment]
Ruby China 全站都在用

> @chenglu 这似乎是 auto-correct gem 的 bug，自动加空格是这个 Ruby China 开发的 gem 的功能，他们只用在 title 上面应该遇不到你这个问题。
> 
> 
> 
> 我可以在我这边修，但那样你也还是不好装。我看看能不能直接交到他们那边去
